### ISSUE TITLE
Dev API keys used even when using a release build

### ISSUE THREAD

**Issue by trypsynth** [opentween/OpenTween#104]
I built OpenTween from source, both as debug and release. However, even when running the release version, the API key shows as OpenTween (dev). This doesn't make sense to me, because if it's a release version, it shouldn't use the dev API key.

**Comment by upsilon** [comment]
The API keys for development and release are switched by git branch, not the build configuration.
When you checkout the `develop` branch, the API key for development is used, and if you're on the `release` branch (which doesn't exist yet), the API key for release is used.
