### ISSUE TITLE
ソースを基準に振り分けをする

### ISSUE THREAD

**Issue by kuyagic** [opentween/OpenTween#23]
ソースで振り分けがほしい。これで自動のツイートが分けれる。

**Comment by upsilon** [comment]
振り分けルールには既に Source の欄があり、`twittbot.net` 等を対象に振り分け可能ですがそれとは違いますか？

**Comment by kuyagic** [comment]
ツイートを右クリックメニューでの引き分けルール作成のサブメニューでのソースからの引き分けがほしい。そしてルール画面のソース欄に自動的にソースを記入すれば便利だと思う。

**Comment by upsilon** [comment]
![2015-02-09 23 37 44](https://cloud.githubusercontent.com/assets/92577/6108318/514d126c-b0b5-11e4-8687-8fbc6460173e.png)

7d1db25a82bc5d33344d5436aee901af501baf3a にてメニュー項目を追加しました。v1.2.5 から反映される予定です。
