### ISSUE TITLE
発言欄での挙動

### ISSUE THREAD

**Issue by MuoTK** [opentween/OpenTween#31]
発言欄で冒頭でスペースを入力するとタイムライン画面へフォーカスが移ってしまう問題
（オプションの「フォーカスを発言欄へロックする」に選択していても発生）

Administrator権限：False
Users権限：True
動作環境:
   オペレーティング システム: Microsoft Windows NT 6.3.9600.0
   共通言語ランタイム: 4.0.30319.34014
   OpenTween.exeのバージョン: 1.2.7-dev

**Comment by upsilon** [comment]
発言欄でスペースキーを入力すると未読発言に移動するのは意図した動作です。
http://osdn.jp/projects/tween/wiki/%E3%82%B7%E3%83%A7%E3%83%BC%E3%83%88%E3%82%AB%E3%83%83%E3%83%88%E3%82%AD%E3%83%BC

投稿するテキストの先頭に空白を入力したい場合は、`Ctrl+Space` で入力して下さい。

**Comment by MuoTK** [comment]
すいません、ありがとうございます。
