### ISSUE TITLE
ユーザー情報の自己紹介のリンク

### ISSUE THREAD

**Issue by momdo** [opentween/OpenTween#33]
OpenTween 1.3.1のプロフィール表示で表示されるユーザー情報の自己紹介に`@ユーザー名`がある場合、そのリンクが

<code>https://twitter.com/%40[ユーザー名]</code>

になってしまい、存在しないページに飛んでしまいます。

<code>https://twitter.com/[ユーザー名]</code>

が適切なリンク形式になると思います。

**Comment by upsilon** [comment]
61666e0507541ca2ed8a0e934448c6b8f4d4cf8a にて修正しました。報告ありがとうございました！
