### ISSUE TITLE
Ctrl+Alt+S shortcut conflicting with Polish keyboard layout

### ISSUE THREAD

**Issue by pitermach** [opentween/OpenTween#45]
Steps to reproduce:

- Switch to the Polish Programmers keyboard layout 
- In the new tweet box, press CTRL+Alt+S.

Expected: "ś" should be entered into the box.
Actual: Fav+Retweet feature is activated.

The result of this is that the only way to type ś, which is a very often used character in Polish, is to paste it from the clipboard. Additionally if I'm typing quickly I end up confirming that I want to RT and favourite whatever I'm replying to as the focus lands on the OK button when the confirmation dialog opens.

The best way to fix this is probably to activate this function only if the focus is in the list of tweets and not the  post body edit box.

**Comment by lukaszgo1** [comment]
@upsilon Can this be looked into and fixed? It is extremely annoying.

**Comment by upsilon** [comment]
Sorry for late reply.
I think it is a good idea to solve this problem by enabling potentially conflicting shortcuts only when focusing on the list. I will try to see if it can actually be fixed by this method.

**Comment by upsilon** [comment]
Note: Ctrl+Alt+* shortcuts currently assigned in OpenTween are as follows

| Shortcut | Polish character | Assigned action |
|--|--|--|
| Ctrl+Alt+S | ś | Favorite and Retweet |
| Ctrl+Alt+R | (Unassigned) | Favorite and Retweet (old style) |
| Ctrl+Alt+H | (Unassigned) | Open selected tweet with user-defined URL pattern |

**Comment by lukaszgo1** [comment]
This build fixes it  for me. @upsilon thanks

**Comment by pitermach** [comment]
I can also confirm it's fixed. Thanks!
