### ISSUE TITLE
「この発言を翻訳」が利用できない

### ISSUE THREAD

**Issue by momdo** [opentween/OpenTween#49]
コンテキストメニューにある「この発言を翻訳」をクリックすると、次のようなメッセージが表示され、ツイートを翻訳することができません。

> TranslateApiException
Method: Translate()
Message: Invalid authentication token. Microsoft DataMarket is retired. Please subscribe to Microsoft Translator, in the Cognitive Services section at https://portal.azure.com. Please visit https://cognitive.uservoice.com/knowledgebase/articles/1128340-announcements-action-required-before-april-30-20 to find detailed instructions.
message id=0759.V2_Rest.Translate.ECAF91F

**Comment by upsilon** [comment]
エラーメッセージの通り、Microsoft DataMarket から提供される Microsoft Translator が廃止されたため、Microsoft Azure の Cognitive Services から提供される API に移行する必要があります。


---

昨年アナウンスがあった当時は Cognitive Service の料金プランに関する説明がさっぱり理解できず（無料試用期間と無料プラン(F0)のうち後者に関する情報が見つけられなかった）、この翻訳機能自体を削除するつもりでいました。
いま Azure のダッシュボードを軽くいじってみた感じでは当時よりはマシになった様で、アクセスキーの発行までは出来たので、あとは実装が済めばなんとか存続できそうです。

**Comment by upsilon** [comment]
c18d7cb9864d1acb18d3e54c4fc931b1ec941b22 にて修正しました。次の v1.3.8 から反映されます
