### ISSUE TITLE
Unable to access Twitter API error

### ISSUE THREAD

**Issue by pitermach** [opentween/OpenTween#84]
To reproduce, just start OpenTween. You will get the following message:

---------------------------
OpenTween
---------------------------
Unable to access Twitter API.

[AuthError]

 * Please confirm the network settings.

 * Please confirm whether your PC's clock is accurate.

    (It may fail to authentication when clock is delayed.)

 * Please re-add the Twitter account in the settings dialog.
---------------------------
OK   
---------------------------

No features work. When trying to add a new account to even attempt to reauthorize I get the following:

---------------------------
Authenticate
---------------------------
Authentication failed

Unauthorized
---------------------------
OK   
---------------------------

I reproduced this with OpenTween version 2.4.3 and 2.4.2. This issue appears to have started on February 25th and is probably affecting every user. It has been reproduced by a number of other people IE in [this Twitter thread](https://twitter.com/doug_lee42/status/1232388067744452608)

**Comment by soumasandesu** [comment]
I also can't perform "Start Authentication" action in a clean OpenTween env

**Comment by soumasandesu** [comment]
btw See more in [this thread](https://twitter.com/kim_upsilon/status/1232453964844564481)

Twitter marked the this app (i.e. the specific OAuth token associated with this app) has been suspended due to violations of their terms and rules

I bet as of today (29 May 2020) this app is still suspended, the whole project can be considered as suspended too.

**Comment by rkingett** [comment]
What about working on Mastodon support instead? I think the Fediverse would be a better investment than Twitter at this point.

**Comment by TheQuinbox** [comment]
This project seems to be seeing some activity, can anyone confirm if Open Tween works again?

**Comment by upsilon** [comment]
OpenTween's API key has been reissued recently, so I'm working to release a usable version within a few weeks. Stay tuned for the upcoming release!

**Comment by trypsynth** [comment]
I'm able to get OpenTween to work again when building from source. Should this issue be closed? The key was fixed, after all.
